{% set name = "joommf" %}
{% set version = "0.8.4" %}
{% set sha256 = "58b9f18768b2d4a9d51a17803f523ce94c11cc64dc7090b75a2cf37a5f91240d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [py27]
  skip: True  # [win32]
  number: 1
  script: pip install --no-deps .

requirements:
  host:
    - python
    - pip
    
  run:
    - python
    - oommfc
    - jupyter
    - pytest

test:
  imports:
    - joommf

  commands:
    - python -c "import sys; import joommf as m; sys.exit(m.test())"

about:
  home: http://joommf.github.io/
  license: BSD 3-clause
  summary: A Python interface to the OOMMF micromagnetic calculator
  license_family: BSD
  license_file: LICENSE

  description: |
    joommf is a meta package for JOOMMF project.

  doc_url: http://joommf.readthedocs.io
  dev_url: https://github.com/joommf/joommf

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - takluyver
    - davidcortesortuno
    - rpep
