travis:
  secure:
    BINSTAR_TOKEN: gsja3bNE6NK5/5kZGbfMMcIOfS9ubQx3KkPfmKA2MLItYiwVF+eTL5e0EDus5KpUR19LpDVwiOMDU+nFA3TEnPxXf4Mgx4DkIoFpsrI5hDCHFZ6xUYhgvOuD0BFVsFPxbFzHU0aDIlE0E/tFrA8raVZxnVHjAeatNG/zDKJP4GQPlWnep5mKbMH/GwkQVGyNXiRV6V5/ehXpFIiEeb3oCokINXs9lf3qXUKeXLEbxOWGcR6NRdD+7BKSLc8XXgv4TZ2udKgNppqbVScCWwABdN9+ysF4yUYEFw0zH5T2jM9n+4p1LXcr8K+rFnYqmXSSpRsdOZi5+WOhccxu9ebLEtBcXyCZbLQoDNNCxUunkKz+Q8LwN5vL9MC+dF3Sgp9I9Qi5mbLI7uFwcqd52sEaCzff9SXiK465+QlhWJK8pkhZHXCn4LWm+ctV63KtP3cd/MG0JtfrNVY8qm0v3q3ttcZnBh1gex5mFESDMGVjk2UkaSBZCCF6W3J73EHKDqeCYE7I7Y+Q1UNv5Ku+TrGSDe2TNUKrN7Qnv+tLPcrgheZaHOA9oiQJP32gxJrLnKTKQi8jFvfLAHnzaoytpBerkYH65kYcC49pwUYPiod4G5tK2RvPK7PvzghFmGBX4IRSvydxX5bGbBGqs8WtoE/Nib8hrrZNyz0WVDYCSk+B+FA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
