travis:
  secure:
    BINSTAR_TOKEN: BSBuus0UoMAVTBLc+yQ4yUrtwDR+y2MfNMjoYPOHtySZb2OVyBTNTDiyz/p9GB9liSX8q9Sp/xbNr2nm3n1pNX/irc/YF18WeXByVYZOXsd2pORJWPhyJtnhmdl7snfNzM/5h0eVG6jYHOjoOzSKQoX93OwkJrLQ7LcKwt8fLEqgoRlwkUWFYL5A6G8A3GxdfRokriREWfmZcgUg+Cqi8cCVD5ToKSdRszjLenycCdHCUlLJMc+vOAfEZrh3rWpyKVwMLkA6OPECwLx3CM4rjhK2RT5Kfz2Gc9AFKlAw8rPWpqjh64XAyDFAMyq2DB6c4VrNmTfbmXvvEtAZ/Edvswjf2kicKW94m1VeAYmSHjPm2ILYDTZsh9Ws7Y9atTHMyJ0OHrLglarEpr53hxAYAbGX1xEonT+E6Z62wZUbmdQ5kEA6aBui6eABkA2RtNVRwbnFXmfG2fje3tZ3ETLsOM6xfwH92Yb3rvSoUWvY/xzTP3OzzqCwGRc8zk7EZIBZUZmlwtg57YjZ/3/aOhOb8NXOOF9/ABeG72KU598F4RvdheH4VrZiRDLTljpxNYWzzitvBSnXidvF2SjuNPdZTokq38p7JCo6Sg8JjBPo604gqmJxSy1+WcjpWbFURnK79LWCN+0BL0KeOm9GUrE3PIiw73kLt4UXKOXk+kN+pf4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
